jenkins_admin_username = "JenkinsAdmin"
environment            = "production"
key_name               = "HelloDevOpsKeyPair"
dockerhub_username     = "bhaktabhusandas"
github_owner           = "BhaktaBhusanDas"
github_repo            = "hello-node-docker"
github_webhook_id      = "564183434"